dragoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('dragons/', views.dragons_index, name='index'),
  path('dragons/<int:dragon_id>', views.dragons_detail, name='detail'),
  path('dragons/create/', views.DragonCreate.as_view(), name="dragons_create"),
  path('dragons/<int:pk>/update', views.DragonUpdate.as_view(), name="dragons_update"),
  path('dragons/<int:pk>/delete', views.DragonDelete.as_view(), name="dragons_delete"),
  path('dragons/<int:dragon_id>/add_burning/', views.add_burning, name='add_burning'),
  path('dragons/<int:dragon_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
  path('dragons/<int:dragon_id>/add_photo/', views.add_photo, name='add_photo'),
  path('toys/', views.ToyList.as_view(), name='toys_index'),
  path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
  path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
  path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
  path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
  path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User


# Create your models here.

class Player(models.Model):
  api_id=models.IntegerField()
  first_name=models.CharField(max_length=50)
  last_name=models.CharField(max_length=50)

class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})

class Dragon(models.Model):
  name = models.CharField(max_length=100)
  breed = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.IntegerField()
  toys = models.ManyToManyField(Toy)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.name} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'dragon_id': self.id} )

TOWNS = (
  ('B', 'Bangladesh'),
  ('L', 'London'),
  ('D', 'Denmark'),
)

class Burning(models.Model):
  date = models.DateField()
  town= models.CharField(
    max_length=1,
    choices=TOWNS,
    default = TOWNS[0][0]
  )
  dragon = models.ForeignKey(Dragon, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_town_display()} on {self.date}"
    
  class Meta:
    ordering = ['-date']

class Photo(models.Model):
  url = models.CharField(max_length=200)
  dragon = models.ForeignKey(Dragon, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for dragon_id: {self.dragon_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Burning

class BurningForm(ModelForm):
  class Meta:
    model = Burning
    fields = ['date', 'town']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
import uuid
import boto3
from .models import Dragon, Toy, Photo
from .forms import BurningForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'dragoncollector'


# Create your views here.
#define the home view

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

def add_burning(request, dragon_id):
    # create the ModelForm using the data in request.POST
  form = BurningForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the dragon_id assigned
    new_burning = form.save(commit=False)
    new_burning.dragon_id = dragon_id
    new_burning.save()
  return redirect('detail', dragon_id=dragon_id)

def home(request):
    return HttpResponse('<h1> yo </h1>')

def about(request):
    return render(request, 'about.html')

@login_required
def dragons_index(request):
    dragons = Dragon.objects.filter(user=request.user)
    return render(request, 'dragons/index.html', { 'dragons': dragons })

@login_required
def dragons_detail(request, dragon_id):
    dragon = Dragon.objects.get(id=dragon_id)
    toys_dragon_doesnt_have = Toy.objects.exclude(id__in = dragon.toys.all().values_list('id'))

    burning_form = BurningForm()
    return render(request, 'dragons/detail.html', { 
      'dragon': dragon, 
      'burning_form' : burning_form,
      'toys': toys_dragon_doesnt_have 
    })

class DragonCreate(LoginRequiredMixin, CreateView):
    model = Dragon
    fields = '__all__'

    def form_valid(self, form):
      # Assign the logged in user (self.request.user)
      form.instance.user = self.request.user
      # Let the CreateView do its job as usual
      return super().form_valid(form)

class DragonUpdate(LoginRequiredMixin, UpdateView):
    model= Dragon
    fields=['breed', 'description', 'age']

class DragonDelete(LoginRequiredMixin, DeleteView):
    model=Dragon
    success_url= '/dragons/'

class ToyList(LoginRequiredMixin, ListView):
  model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
  model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
  model = Toy
  fields = '__all__'

class ToyUpdate(LoginRequiredMixin, UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(LoginRequiredMixin, DeleteView):
  model = Toy
  success_url = '/toys/'

@login_required
def assoc_toy(request, dragon_id, toy_id):
  # Note that you can pass a toy's id instead of the whole object
  Dragon.objects.get(id=dragon_id).toys.add(toy_id)
  return redirect('detail', dragon_id=dragon_id)

@login_required
def add_photo(request, dragon_id):
  # photo-file will be the "name" attribute on the <input type="file">
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    # need a unique "key" for S3 / needs image file extension too
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    # just in case something goes wrong
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      # build the full url string
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      # we can assign to dragon_id or dragon (if you have a dragon object)
      photo = Photo(url=url, dragon_id=dragon_id)
      photo.save()
    except:
      print('An error occurred uploading file to S3')
  return redirect('detail', dragon_id=dragon_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About the Dragon Collector</h1>
<hr />
<p>Hire the Dragon Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Dragon Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;DragonCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
          <li><a href="{% url 'dragons_create' %}">Add a Dragon</a></li>
          <li><a href="{% url 'index' %}">View All My Dragons</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Dragon Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/dragons/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dragon Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dragon.name }}</span>
        <p>Breed: {{ dragon.breed }}</p>
        <p>Description: {{ dragon.description }}</p>
        {% if dragon.age > 0 %}
          <p>Age: {{ dragon.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dragons_update' dragon.id %}">Edit</a>
        <a href="{% url 'dragons_delete' dragon.id %}">Delete</a>
      </div>
    </div>
    {% for photo in dragon.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
  {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
  {% endfor %}

  <form action="{% url 'add_photo' dragon.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <input type="submit" class="btn" value="Upload Photo">
</form>
  </div>
  
  <div class="col s6">
    <form action="{% url 'add_burning' dragon.id %}" method="post">
      {% csrf_token %}
      {{ burning_form.as_p }}
      <input type="submit" class="btn" value="Add Burning">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Town</th></tr>
      </thead>
      <tbody>
        {% for burning in dragon.burning_set.all %}
          <tr>
            <td>{{burning.date}}</td>
            <td>{{burning.get_town_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ dragon.name }}'s Toys</h3>
    {% if dragon.toys.count %}
      {% for toy in dragon.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->

  <div class="col s6">
      <h3>Available Toys</h3>
      {% if toys.count %}
        {% for toy in toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_toy' dragon.id toy.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{dragon.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>
</div>
<script> 
  var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });

  var selectEl = document.getElementById('id_town');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dragons/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Dragon List</h1>

{% for dragon in dragons %}
  <a href="{% url 'detail' dragon.id %}">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dragon.name }}</span>
        <p>Breed: {{ dragon.breed }}</p>
        <p>Description: {{ dragon.description }}</p>
        {% if dragon.age > 0 %}
          <p>Age: {{ dragon.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/dragon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dragon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' dragon.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dragon_form.html
{% extends 'base.html' %}


{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Dragon</h1>
{% endif %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    <tbody>
      {{ form.as_table }}
    </tbody>
  </table>
  <input type="submit" value="Submit" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/toy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}